[package]
name = "lie"
version = "0.1.0"
description = "Lie App"
authors = ["jwyxym"]
edition = "2024"

[lib]
name = "lie_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3.1.2", features = ["cookies"] }
anyhow = "1.0.100"
scraper = "0.23.1"
urlencoding = "2.1.3"
lazy_static = "1.5.0"
